### ISSUE TITLE
Error test query

### ISSUE THREAD

**Issue by azzahrah** [kno10/reversegeocode#2]
Exception in thread "main" java.lang.IllegalArgumentException: Size exceeds Integer.MAX_VALUE
	at java.base/sun.nio.ch.FileChannelImpl.map(FileChannelImpl.java:941)
	at com.kno10.reversegeocode.query.ReverseGeocoder.reopen(ReverseGeocoder.java:101)
	at com.kno10.reversegeocode.query.ReverseGeocoder.<init>(ReverseGeocoder.java:91)
	at com.kno10.reversegeocode.query.RunTestQueries.main(RunTestQueries.java:29)

**Comment by kno10** [comment]
This is a built-in limit of Java memory mapping.
Use a lower resolution, or rewrite the code to use multiple maps.
